params:
  learning_rate: 0.07343892881373013
  max_depth: 4
  min_child_weight: 3
  n_estimators: 37
  subsample: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    BQEivyuq1z8=
target: 0.30726910426032134
